### ISSUE TITLE
upload a model to huggingface

### ISSUE THREAD

**Issue by blane187gt** [Bebra777228/clear2#9]
can you make a feature after finish the training it will zip the model file  index, pth and upload it to huggingface?

if code to the zip file, i have tho

import zipfile
import os

def zip_files(file_paths, zip_filename):

  with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for file_path in file_paths:
      if os.path.isfile(file_path):
        zipf.write(file_path, os.path.basename(file_path))

# Example usage:
file_paths = ['pth_file.pth', 'index_file.index']  # Replace with your actual file paths
model_name = 'name_model'

zip_files(file_paths, model_name)
print(f"{model_name} Files success zipped to {model_name}")

**Comment by Bebra777228** [comment]
This repository is temporary, just for testing, but I will consider it in the [main repository](https://github.com/Bebra777228/TrainVocModel-EN).
